# Generated by Django 3.1 on 2020-09-27 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coldstorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coldstorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=155)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('total_storage', models.IntegerField()),
                ('storage_left', models.IntegerField()),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('crop_type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
                ('storage_name', models.CharField(default='.', max_length=155)),
            ],
        ),
        migrations.DeleteModel(
            name='displayusername',
        ),
    ]
