# Generated by Django 3.1 on 2020-08-19 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coldstorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coldstorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=155)),
                ('date_modeified', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('total_storage', models.IntegerField()),
                ('storage_left', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='displayusername',
        ),
    ]
