# Generated by Django 3.1 on 2020-08-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coldstorage', '0002_auto_20200819_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldstorage',
            old_name='date_modeified',
            new_name='date_modified',
        ),
    ]
