# Generated by Django 3.1 on 2020-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldstorage', '0003_auto_20200819_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldstorage',
            name='phone',
            field=models.CharField(default=91, max_length=12),
            preserve_default=False,
        ),
    ]
