# Generated by Django 3.1 on 2020-08-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldstorage', '0004_coldstorage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldstorage',
            name='email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
