# Generated by Django 3.1 on 2020-09-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldstorage', '0005_coldstorage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('crop_type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('address', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
